#!/bin/sh

echo "Init TTY ..."

if ! [ /dev/tty1 -ef /dev/console ]; then
    lxc_console="console"
fi

s_args=""
for tty in $lxc_console tty1 ttyS0 ttyAMA0 hvc0; do
    if [ -e /dev/$tty ] && { echo "" >> "/dev/$tty" ; } 2>/dev/null ; then
        s_args="${s_args:+${s_args} }s/^#$tty:\(.*\)/$tty:\1/;"
    else
        s_args="${s_args:+${s_args} }s/^$tty:\(.*\)/#$tty:\1/;"
    fi
done
[ -z "$s_args" ] ||
    { sed -i "$s_args" /etc/inittab && kill -HUP 1; }

exit 0
