#!/bin/sh

for tok in $(cat /proc/cmdline)
do
    export $tok
done

case "$1" in
    start)
        for i in $(seq 3)
        do
            for dev in $(ls /sys/class/net)
            do
                if [ "$dev" != "lo" ]; then
                    echo "Initialize $dev ..."
                    TRIES=12
                    if [ -n "$addr" ]; then
                        if [ -n "$mac" ]; then
                            dev_mac=$(cat /sys/class/net/$dev/address)
                            if [ "$mac" != "$dev_mac" ]; then
                                continue
                            fi
                        fi
                        /sbin/ifconfig $dev $addr netmask $mask
                        /sbin/ip route add default via $gateway
                        sleep 1
                        for t in $(seq $TRIES); do
                            ping -c 1 $dest
                            if [ "$?" -eq "0" ]; then
                                echo $dev > /tmp/admin_nic
                                exit 0
                            fi
                            sleep 1
                        done
                        /sbin/ip route del default via $gateway
                        /sbin/ifconfig $dev 0 down
                    else
                        /sbin/udhcpc -t $TRIES -T 3 -n -i $dev
                        if [ "$?" -eq "0" ]; then
                            echo $dev > /tmp/admin_nic
                            exit 0
                        fi
                    fi
                fi
            done
        done
        ;;
    stop|restart|reload)
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?
